# Generated by Django 2.2.17 on 2021-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/media/products_images/default.png', upload_to='static/media/products_images'),
        ),
    ]
