# Generated by Django 2.2.17 on 2021-02-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210212_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/media/products_images/default.png', upload_to='products_images'),
        ),
    ]
