# Generated by Django 2.2.17 on 2021-03-29 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20210329_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
        migrations.RemoveField(
            model_name='basket',
            name='created_timestamp',
        ),
        migrations.AddField(
            model_name='basket',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL),
        ),
    ]
